### ISSUE TITLE
tests don't generate AppMaps

### ISSUE THREAD

**Issue by miketheman** [getappmap/appmap-python#244]
Follows #236

The now-vendored `wrapt` raises this exception when installing:

```python
Error processing line 1 of /opt/warehouse/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/wrapt/wrappers.py", line 613, in __call__
      return self._self_wrapper(self.__wrapped__, instance,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/importer.py", line 234, in wrapped_exec_module
      Importer.do_import(*args, **kwargs)
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/importer.py", line 203, in do_import
      instrument_functions(fc)
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/importer.py", line 181, in instrument_functions
      wrapt.wrap_function_wrapper(filterable.obj, fn_name, new_fn)
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/wrapt/wrappers.py", line 956, in wrap_function_wrapper
      return wrap_object(module, name, FunctionWrapper, (wrapper,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/wrapt/wrappers.py", line 902, in wrap_object
      (parent, attribute, original) = resolve_path(module, name)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/wrapt/wrappers.py", line 890, in resolve_path
      original = lookup_attribute(parent, attribute)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/warehouse/lib/python3.11/site-packages/_appmap/wrapt/wrappers.py", line 886, in lookup_attribute
      return getattr(parent, attribute)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: type object 'DistutilsMetaFinder' has no attribute 'spec_for_test'
```

**Comment by apotterri** [comment]
@miketheman Thanks for the follow up. This looks like it might be a problem in `appmap`'s implementation, something that's unrelated to `wrapt`, and isn't specific to 3.11.

What command are you running that's producing this stack trace? Does it work in a 3.10 environment?

**Comment by miketheman** [comment]
You can give it a shot - it's pypa/warehouse and I'd added appmap to requirements/dev.txt and ran `make tests` as a way to determine if it can even be installed.

**Comment by apotterri** [comment]
Thanks for this, having code to work with is a big help. I'll take a look.

**Comment by apotterri** [comment]
Turns out the errors were caused by the default config generated by `appmap`. It included all the packages in the venv, which isn't necessary and causes problems. I opened an issue for this: https://github.com/getappmap/appmap-python/issues/245 .

I created a better config, and that gets rid of the error. Running tests don't generate AppMaps, though, and I'm looking into why that is. Once I figure it out, I'll fork the `warehouse` repo and push my changes to a branch.

**Comment by apotterri** [comment]
I forked pypi/warehouse, and created a branch that generates AppMaps when the tests are run: https://github.com/apotterri/warehouse/tree/1bdfb01350e5ba03975ea90d7c01012c7bbd3734 .

When I tried to run all the tests, it got stuck trying to run `tests/unit/test_db.py`. I don't know if this is a particularly long-running test, or if AppMap is having trouble recording it. Your best bet is probably going to be starting small, picking a couple of tests you're interested in recording. Once that's working, we can look at expanding coverage.

Since we're now able to generate AppMaps, I'm going to close this issue. We can open a new one if you run into more trouble.

Thanks!
